# Generated by Django 4.1.7 on 2023-02-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('temata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temata')),
            ],
        ),
    ]
